name: Build Docker image for master, dev and stable branches

on:
  push:
    branches: [master, dev, stable]
    schedule:
      # run CI every day even if no PRs/merges occur
      - cron:  '0 12 * * *'

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@master

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: creased/${{github.repository}}/testing
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
          push: true

